parameters:
    # Common hyperparameters
    mode: 'test'
    load: false
    name: 'FNN_warehouse'
    algorithm: PPO
    port: 8000
    render: true
    render_delay: 0.1
    env_type: 'warehouse'
    flicker: false
    max_steps: 2.0e+6
    max_episode_steps: 5.0e+3
    num_frames: 1
    num_epoch: 3
    gamma: 0.99
    lambda: 0.95
    learning_rate: 2.5e-4
    batch_size: 32
    memory_size: 128
    train_frequency: 1
    save_frequency: 1.0e+3
    summary_frequency: 1.0e+3
    tensorboard: true
    iteration: -1
    episode: 0
    obs_type: 'vector'
    obs_size: 625
    frame_height: 25
    frame_width: 25

    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 2
    num_fc_units: [128, 64]
    # Convolutional module
    convolutional: false
    num_conv_layers: 2
    num_filters: [32, 16]
    kernel_sizes: [2, 2]
    strides: [1, 1]
    # Recurrent module
    recurrent: false
    num_rec_units: 128
    seq_len: 8

    # INFLUENCE MODEL
    influence: false
    inf_box_height: 84
    inf_box_width: 84
    inf_box_center: [[0, 0]]
    inf_frame_height: 84
    inf_frame_width: 84
    inf_num_frames: 1
    inf_num_predictors: 1
    # Influence fully connected module
    inf_num_fc_layers: 0
    inf_num_fc_units: [128]
    # Influence convolutional module
    inf_num_conv_layers: 3
    inf_num_filters: [32, 64, 64]
    inf_kernel_sizes: [8, 3, 2]
    inf_strides: [4, 2, 1]
    # Influence recurrent module
    inf_num_rec_units: 512
    inf_seq_len: 4

    # PPO only
    num_workers: 1
    beta: 1.0e-2
    epsilon: 0.1
    time_horizon: 128
    c1: 1