FROM python:3.7
MAINTAINER Miguel Suau <miguel.suau@gmail.com>

WORKDIR ./

RUN git clone https://github.com/INFLUENCEorg/flow

RUN cd flow

irements.txt /requirements.txt

RUN python -m pip install --upgrade pip

RUN pip install -r ./requirements.txt

COPY ./ ./

RUN chmod +x /runners/experiment.py
