parameters:
    main:
        # Common hyperparameters
        simulator: 'partial'
        env: 'traffic'
        name: 'default_traffic'
        influence_model: 'nn'
        obs_size: 40
        num_actions: 2
        total_steps: 2.0e+6
        save_frequency: 1.0e+5
        num_workers: 8
        beta: 1.0e-2
        epsilon: 0.1
        rollout_steps: 64
        obs_type: 'vector'
        c1: 1
        num_epoch: 3
        gamma: 0.99
        lambda: 0.95
        learning_rate: 2.5e-4
        batch_size: 32
        memory_size: 128
        eval_freq: 1.0e+5
        eval_steps: 1.0e+4
        num_workers: 8
        framestack: false
        load_policy: false
        
        load: false
        render: false
        fully_connected: true
        num_fc_layers: 2
        num_fc_units: [64, 32]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: false
        num_rec_units: 32
        seq_len: 8
        # Influence-aware memory
        influence: false
        # Attention
        attention: false
        automatic_dpatch: false
        manual_dpatch: true
        num_att_units: [256]
        # D-set
        inf_num_predictors: 16
        dset: [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
        # Influence fully connected module
        inf_num_fc_layers: 0
        inf_num_fc_units: [128]
        # Influence recurrent module
        inf_num_rec_units: 8
        inf_seq_len: 8


    influence:
        # Common hyperparameters
        seq_len: 300
        episode_length: 300
        data_path: '../influence/data/traffic/'
        lr: 1.0e-3
        n_epochs1: 2000
        n_epochs2: 500
        batch_size: 32
        hidden_memory_size: 8
        input_size: 40
        output_size: 1
        n_sources: 4
        checkpoint_path: '../influence/models/traffic/model'
        aug_obs: False
        load_model: False
        curriculum: False
        dataset_size1: 2.0e+4
        dataset_size2: 1.0e+4
        train_freq: 5.0e+6