parameters:
    # Common hyperparameters
    mode: 'train'
    load: False
    name: 'partial'
    algorithm: PPO
    env: 'warehouse'
    simulator: 'partial'
    flicker: false
    max_steps: 2.0e+6
    max_episode_steps: 5.0e+3
    num_epoch: 3
    gamma: 0.99
    lambda: 0.95
    learning_rate: 2.5e-4
    batch_size: 32
    memory_size: 128
    train_frequency: 1
    influence_train_frequency: 1.0e+5
    save_frequency: 1.0e+5
    summary_frequency: 1.0e+4
    tensorboard: true
    iteration: -1
    episode: 0
    obs_type: 'vector'
    obs_size: 65

    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 2
    num_fc_units: [128, 64]
    # Convolutional module
    convolutional: false
    num_conv_layers: 2
    num_filters: [32, 16]
    kernel_sizes: [2, 2]
    strides: [1, 1]
    # Recurrent module
    recurrent: false
    num_rec_units: 128
    seq_len: 8

    # INFLUENCE MODEL
    influence: false

    # PPO only
    num_workers: 8
    beta: 1.0e-1
    epsilon: 0.1
    time_horizon: 16
    c1: 1