parameters:
    main:
        # Common hyperparameters
        simulator: 'global'
        env: 'warehouse'
        obs_size: 37
        time_horizon: 8
        num_actions: 4
        name: 'global_warehouse_nomem'
        influence_model: None
        fully_connected: true
        num_fc_layers: 2
        num_fc_units: [256, 128]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: false