parameters:
    main:
        # Common hyperparameters
        simulator: 'global'
        fully_connected: true
        num_fc_layers: 2
        num_fc_units: [256, 256]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: False
        num_rec_units: 256
        seq_len: 8
        num_workers: 8
        # Influence-aware memory
        influence: false