parameters:
    main:
        # Common hyperparameters
        simulator: 'global'
        fully_connected: true
        num_fc_layers: 2
        num_fc_units: [256, 128]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: False
        num_rec_units: 256
        seq_len: 8
        num_workers: 8
        # Influence-aware memory
        influence: true
        # Attention
        attention: false
        automatic_dpatch: false
        manual_dpatch: true
        num_att_units: [256]
        # D-set
        inf_num_predictors: 16
        dset: [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
        # Influence fully connected module
        inf_num_fc_layers: 0
        inf_num_fc_units: [128]
        # Influence recurrent module
        inf_num_rec_units: 8
        inf_seq_len: 8