parameters:
    main:
        # Common hyperparameters
        simulator: 'local'
        env: 'warehouse'
        obs_size: 69
        rollout_steps: 8
        num_actions: 4
        name: 'local_warehouse_iam'
        influence_model: 'nn'
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [512]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: true
        num_rec_units: 512
        seq_len: 8
        num_workers: 8
        epsilon: 0.1
        beta: 0.01
        render: False
        dset: [1, 2, 3, 4, 5, 7, 13, 14, 20, 21, 27, 28, 34, 35, 41, 43, 44, 45, 46, 47, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]
        policy: 'IAMPolicy'

    influence:
        # Common hyperparameters
        seq_len: 100
        episode_length: 100
        data_path: '../influence/data/warehouse/'
        lr: 1.0e-3
        num_epochs: 500
        batch_size: 32
        hidden_memory_size: 64
        input_size: 69
        output_size: 6
        n_sources: 4
        checkpoint_path: '../influence/models/warehouse/model'
        aug_obs: False
        load_model: False
        curriculum: False
        dataset_size: 5.0e+4