parameters:
    main:
        # Common hyperparameters
        name: 'partial_warehouse'
        influence_model: 'nn'
        env: 'warehouse'
        obs_size: 37
        rollout_steps: 8 
        num_actions: 4
        simulator: 'local'
        fully_connected: true
        num_fc_layers: 1
        num_fc_units: [512]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: true
        num_rec_units: 256
        seq_len: 8

    influence:
        # Common hyperparameters
        seq_len: 100
        episode_length: 100
        data_path: '../influence/data/warehouse/'
        lr: 1.0e-3
        num_epochs: 1
        batch_size: 32
        hidden_memory_size: 64
        input_size: 37
        output_size: 4
        n_sources: 4
        checkpoint_path: '../influence/models/warehouse/model'
        aug_obs: False
        load_model: False
        curriculum: False
        dataset_size: 1.0e+4
        train_freq: 3.0e+6
