parameters:
    main:
        # Common hyperparameters
        name: 'partial_iam_warehouse'
        influence_model: 'nn'
        env: 'warehouse'
        obs_size: 69
        num_actions: 4
        simulator: 'partial'
        fully_connected: true
        num_fc_layers: 2
        num_fc_units: [512, 256]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: false
        influence: true
        # Attention
        attention: false
        automatic_dpatch: true
        manual_dpatch: false
        # Influence recurrent module
        inf_num_rec_units: 128
        time_horizon: 8
        inf_seq_len: 8

    influence:
        # Common hyperparameters
        seq_len: 100
        episode_length: 100
        data_path: '../influence/data/warehouse/'
        lr: 1.0e-3
        n_epochs1: 500
        n_epochs2: 50
        batch_size: 32
        hidden_memory_size: 64
        input_size: 69
        output_size: 6
        n_sources: 4
        checkpoint_path: '../influence/models/warehouse/model'
        aug_obs: False
        load_model: False
        curriculum: False
        dataset_size1: 5.0e+4
        dataset_size2: 1.0e+4
        train_freq: 3.0e+6