parameters:
    main:
        # Common hyperparameters
        mode: 'train'
        load: False
        name: 'partial'
        algorithm: PPO
        env: 'warehouse'
        simulator: 'partial'
        max_steps: 2.0e+6
        max_episode_steps: 5.0e+3
        train_frequency: 1
        save_frequency: 1.0e+5
        summary_frequency: 1.0e+4
        tensorboard: true
        iteration: -1
        episode: 0
        num_workers: 8
        max_steps: 2.0e+6
        beta: 1.0e-1
        epsilon: 0.1
        time_horizon: 16
        obs_type: 'vector'
        obs_size: 41
        c1: 1
        num_epoch: 3
        gamma: 0.99
        lambda: 0.95
        learning_rate: 2.5e-4
        batch_size: 32
        memory_size: 128
        influence_model: 'nn'
        eval_freq: 1.0e+5
        eval_steps: 1.0e+4

        fully_connected: true
        num_fc_layers: 2
        num_fc_units: [256, 128]
        # Convolutional module
        convolutional: false
        # Recurrent module
        recurrent: False
        num_rec_units: 128
        seq_len: 16
        # Influence-aware memory
        influence: false

    influence:
        # Common hyperparameters
        seq_len: 100
        episode_length: 100
        data_path: '../influence/data/warehouse/'
        lr: 1.0e-3
        n_epochs: 2000
        batch_size: 32
        hidden_memory_size: 8
        input_size: 16
        output_size: 25
        n_sources: 8
        checkpoint_path: '../influence/models/warehouse/model'
        aug_obs: False
        load_model: False
        curriculum: False
        dataset_size: 5.0e+4
        train_freq: 3.0e+6