parameters:
    # Common hyperparameters
    seq_len: 200
    episode_length: 200
    data_path: '../influence/data/traffic/'
    lr: 1.0e-3
    n_epochs: 1500
    batch_size: 16
    hidden_memory_size: 6
    input_size: 40
    output_size: 1
    n_sources: 4
    checkpoint_path: 'models/influence'
    aug_obs: False
    load_model: False
    curriculum: False
    dataset_size: 1.0e+4