warehouse:
  n_rows: 37 # n_robots_row*(domain_size-1) + 1
  n_columns: 37 # n_robots_column*(domain_size-1) + 1
  n_robots_row: 6
  n_robots_column: 6
  distance_between_shelves: 6
  robot_domain_size: [7, 7]
  prob_item_appears: 0.03
  learning_robot_id: 20 # the learning robot
  obs_type: 'image'
  n_steps_episode: 100
  render: false
  render_delay: 0.5