parameters:
    main:
        # Common hyperparameters
        env: 'traffic'
        simulator: 'global'
        name: 'global_traffic'
        influence_model: None
        eval_steps: 5.0e+4
        num_workers: 1