parameters:
    main:
        # Common hyperparameters
        env: 'traffic'
        simulator: 'local'
        name: 'uniform_traffic'
        influence_model: 'uniform'
        num_workers: 8
        policy: 'IAMPolicy'
        seq_len: 8
        dset: null

    influence:
        probs: [0.5, 0.5, 0.5, 0.5]
        seq_len: 1
        episode_length: 300